# .github/workflows/deploy-app-to-azure-app-service.yml

name: Deploy ASP.NET Core MVC app to Azure App Service
on:
  push:
    branches:
      - main

env:
  SOURCE_DIR: ${{ github.workspace }}/src
  OUTPUT_DIR: publish # Relative to a current working directory
  DOTNET_VERSION: 5.0.x # Set .NET version to use
  NODE_VERSION: 12.x # Set Node.js version to use

jobs:
  build:
    # Find more virtual environments
    # https://www.dotnetthailand.com/programming-cookbook/github-actions/github-actions-fundamentals#findmorevirtualenvironments
    runs-on: ubuntu-latest
    # You can use default run to set default working directory
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun
    defaults:
      run:
        working-directory: ${{ env.SOURCE_DIR }}

    steps:
      - name: Checkout the latest source code from ${{ github.ref }} commit
        uses: actions/checkout@v2

      - name: Set YARN_WORKSPACES_EXIST variable
        run: |
          workspaces_info_result=$(yarn workspaces info > /dev/null 2>&1; echo $?; exit 0)
          if [ $workspaces_info_result -eq 0 ]; then echo "YARN_WORKSPACES_EXIST=1" >> $GITHUB_ENV; fi

      - name: Use Node.js version ${{ env.NODE_VERSION }}
        if: ${{ env.YARN_WORKSPACES_EXIST == 1 }}
        uses: actions/setup-node@v2 # https://github.com/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build all Node.js projects if Yarn Workspaces exists
        if: ${{ env.YARN_WORKSPACES_EXIST == 1 }}
        run: |
          yarn install
          yarn workspaces run build

      - name: Setup .NET SDK version ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1 # https://github.com/actions/setup-dotnet
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Nuget packages
        run: |
          dotnet restore NopCommerce.sln

      - name: Build plugins # You cannot refer to the plugins from building Nob.Web because it would create circular references.
        run: |
          dotnet build Plugins/Nop.Plugin.Payments.CheckMoneyOrder/Nop.Plugin.Payments.CheckMoneyOrder.csproj --configuration Release
          dotnet build Plugins/Nop.Plugin.Payments.Manual/Nop.Plugin.Payments.Manual.csproj --configuration Release
          dotnet build Plugins/Nop.Plugin.Payments.PayPalCommerce/Nop.Plugin.Payments.PayPalCommerce.csproj --configuration Release
          dotnet build Plugins/Nop.Plugin.Payments.PayPalStandard/Nop.Plugin.Payments.PayPalStandard.csproj --configuration Release

      - name: Publish a .NET project to ${{ env.OUTPUT_DIR }}
        run: |
          dotnet publish "Presentation/Nop.Web/Nop.Web.csproj" --configuration Release --output ${{ env.OUTPUT_DIR }} --no-restore

      # Before downloading a publish profile,
      # please make sure you have set WEBSITE_WEBDEPLOY_USE_SCM in App Service configuration to true.
      - name: Deploy to Azure App Service code publish
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{env.SOURCE_DIR}}/${{ env.OUTPUT_DIR }}